### ISSUE TITLE
Improve testing infra

### ISSUE THREAD

**Issue by bartlomieju** [bartlomieju/deno-postgres#10]
Waiting for `tearDown` and `setUp` from denoland/deno_std#128

Then we need to prepare methods to quickly setup new tables

**Comment by bartlomieju** [comment]
@hayd, do you know the status with this issue?

**Comment by hayd** [comment]
I think Ry is a no. The solution is to rewrite in the style of std's fs/walk_test.ts

**Comment by hayd** [comment]
I'll improve this after #27.
