### ISSUE TITLE
Authentication handling

### ISSUE THREAD

**Issue by bartlomieju** [bartlomieju/deno-postgres#4]
Both cleartext password and MD5 should be handled:
https://github.com/bartlomieju/deno-postgres/blob/master/connection.ts#L95:L112

**Comment by avinashdvv** [comment]
@bartlomieju can i take this issue?

**Comment by bartlomieju** [comment]
@avinashdvv are you working on this?

**Comment by avinashdvv** [comment]
> @avinashdvv are you working on this?

yes, I started working on this. In the worst case scenario, I will try to complete this by Sunday.

**Comment by bartlomieju** [comment]
Cleartext passwords are already handled, MD5 is still pending. I'll look into into next week.

**Comment by bartlomieju** [comment]
Done in 093b59d890e36a27a4c98c6afcbbd9dde639c723
