### ISSUE TITLE
Unexpected syntax error in query

### ISSUE THREAD

**Issue by runnerSnail** [bartlomieju/deno-postgres#54]
```typescript
import pool from "../model/db.ts";
export default async function  transaction(sql:string):Promise<string>{
    let client,affect;
        try {
            client = await pool.connect();
            await client.query("BEGIN");
            affect = await client.query(sql);
            await client.query("COMMIT");
        } catch (error) {
            await client.query("ROLLBACK");
            console.log(error);
            affect = null;
        }finally{
            client.release();
        }
        return affect;
}
transaction('select * from article order by create_time desc limit 10 offset  0;')
```

error message

`PostgresError: syntax error at or near " offset  0`

**Comment by bartlomieju** [comment]
![](https://files.gitter.im/deno-postgres/community/BF3P/image.png)

**Comment by runnerSnail** [comment]
Sorry, what's the problem？😊

**Comment by runnerSnail** [comment]
## Adjust my SQL statements
```sql
select * from article limit  10  offset  0 order by create_time desc;
```

## postico is wrong
![deno run](https://cdn.nlark.com/yuque/0/2019/jpeg/303359/1558947861735-915fba49-d082-4cd5-b3d4-4af16bbe0751.jpeg)
## deno run right
![postico run ](https://cdn.nlark.com/yuque/0/2019/jpeg/303359/1558947940473-5ca626b2-5c65-485b-a68d-7f3238636d42.jpeg)

**Comment by bartlomieju** [comment]
@runnerSnail I haven't had time to check this issue yet.

I believe you have extra whitespaces in your queries, can you check if removing them solves the problem?

**Comment by runnerSnail** [comment]
yes,one more space, and it's strict。
but hopefully,deno-postgres can handle whitespace。
thx～ deno-postgres helped me a lot

**Comment by bartlomieju** [comment]
> yes,one more space, and it's strict。
> but hopefully,deno-postgres can handle whitespace。
> thx～ deno-postgres helped me a lot

Glad to hear that - I think handling extra whitespace is currently out-of-scope, but maybe I'll revisit later. Closing this issue for now.
